# Preguntas originales de práctica (no son ítems oficiales del ICFES).

TEMAS = [
    {
        "id": "Aritmetica",
        "titulo": "Aritmética",
        "subtitulo": "Operaciones, múltiplos y números enteros",
        "descripcion": "Cálculo básico, orden de operaciones y problemas con enteros, fracciones y restos.",
        "preguntas": [
            {
                "enunciado": "Un estudiante compra 3 cuadernos a $4.500 cada uno y 2 esferos a $1.200 cada uno. Si paga con un billete de $20.000, ¿cuánto recibe de vueltos?",
                "opciones": {"A": "$3.100", "B": "$4.100", "C": "$5.100", "D": "$6.500"},
                "respuesta": "B",
                "explicacion": "3×4.500=13.500 y 2×1.200=2.400; total 15.900. Vueltos: 20.000−15.900=4.100.",
            },
            {
                "enunciado": "El resultado de 48 ÷ 6 + 5 × (9 − 3) es:",
                "opciones": {"A": "18", "B": "38", "C": "78", "D": "53"},
                "respuesta": "B",
                "explicacion": "Paréntesis: 9−3=6. Luego 48÷6=8 y 5×6=30. Suma: 8+30=38.",
            },
            {
                "enunciado": "Se empacan 250 naranjas en cajas de 18. ¿Cuántas cajas llenas se obtienen y cuántas naranjas sobran?",
                "opciones": {"A": "13 cajas y 16 naranjas", "B": "14 cajas y 0 naranjas", "C": "13 cajas y 14 naranjas", "D": "12 cajas y 16 naranjas"},
                "respuesta": "A",
                "explicacion": "250=18×13+16, porque 18×13=234 y 250−234=16.",
            },
            {
                "enunciado": "La temperatura a las 6 a. m. era −3 °C. Subió 7 °C al mediodía y luego bajó 12 °C en la noche. ¿Cuál fue la temperatura nocturna?",
                "opciones": {"A": "−8 °C", "B": "−2 °C", "C": "4 °C", "D": "16 °C"},
                "respuesta": "A",
                "explicacion": "−3+7=4 y 4−12=−8 °C.",
            },
            {
                "enunciado": "Un número entero positivo N deja residuo 3 al dividirlo entre 5 y residuo 2 al dividirlo entre 4. Si N está entre 20 y 40, ¿cuál es N?",
                "opciones": {"A": "23", "B": "27", "C": "33", "D": "38"},
                "respuesta": "D",
                "explicacion": "38=5×7+3 y 38=4×9+2.",
            },
            {
                "enunciado": "El máximo común divisor de 48 y 36 es:",
                "opciones": {"A": "6", "B": "8", "C": "12", "D": "18"},
                "respuesta": "C",
                "explicacion": "48=2⁴×3 y 36=2²×3²; MCD=2²×3=12.",
            },
            {
                "enunciado": "¿Cuál es el mínimo común múltiplo de 8 y 12?",
                "opciones": {"A": "16", "B": "24", "C": "36", "D": "48"},
                "respuesta": "B",
                "explicacion": "8=2³ y 12=2²×3; MCM=2³×3=24.",
            },
            {
                "enunciado": "El valor de 3/4 + 5/6 es:",
                "opciones": {"A": "8/10", "B": "15/24", "C": "19/12", "D": "4/5"},
                "respuesta": "C",
                "explicacion": "3/4=9/12 y 5/6=10/12; suma 19/12.",
            },
            {
                "enunciado": "Un bus recorre 180 km en 3 horas a velocidad constante. ¿Cuántos kilómetros recorre en 5 horas al mismo ritmo?",
                "opciones": {"A": "240 km", "B": "280 km", "C": "300 km", "D": "360 km"},
                "respuesta": "C",
                "explicacion": "Velocidad 60 km/h. En 5 h: 300 km.",
            },
            {
                "enunciado": "¿Cuál de estos números es primo?",
                "opciones": {"A": "51", "B": "57", "C": "59", "D": "91"},
                "respuesta": "C",
                "explicacion": "51=3×17, 57=3×19, 91=7×13. 59 no tiene divisores propios.",
            },
            {
                "enunciado": "El valor absoluto de −17 + 5 es:",
                "opciones": {"A": "12", "B": "22", "C": "−12", "D": "17"},
                "respuesta": "A",
                "explicacion": "−17+5=−12 y |−12|=12.",
            },
            {
                "enunciado": "3,2 × 10⁴ escrito como número decimal es:",
                "opciones": {"A": "320", "B": "3.200", "C": "32.000", "D": "320.000"},
                "respuesta": "C",
                "explicacion": "3,2×10.000=32.000.",
            },
            {
                "enunciado": "La suma de tres enteros consecutivos es 48. ¿Cuál es el mayor de ellos?",
                "opciones": {"A": "15", "B": "16", "C": "17", "D": "18"},
                "respuesta": "C",
                "explicacion": "n+(n+1)+(n+2)=48 → 3n+3=48 → n=15. El mayor es 17.",
            },
            {
                "enunciado": "¿Cuál es el residuo de dividir 1.000 entre 7?",
                "opciones": {"A": "0", "B": "1", "C": "4", "D": "6"},
                "respuesta": "D",
                "explicacion": "7×142=994 y 1.000−994=6.",
            },
            {
                "enunciado": "Un tanque tiene 3/5 de su capacidad. Se extrae 1/4 de lo que había. ¿Qué fracción de la capacidad total queda?",
                "opciones": {"A": "9/20", "B": "7/20", "C": "1/5", "D": "3/10"},
                "respuesta": "A",
                "explicacion": "Se extrae (1/4)×(3/5)=3/20. Queda 3/5−3/20=12/20−3/20=9/20.",
            },
            {
                "enunciado": "Si 2⁵ × 2³ = 2ⁿ, el valor de n es:",
                "opciones": {"A": "8", "B": "15", "C": "16", "D": "32"},
                "respuesta": "A",
                "explicacion": "Al multiplicar potencias de igual base se suman exponentes: 5+3=8.",
            },
        ],
    },
    {
        "id": "Porcentajes y proporcionalidad",
        "titulo": "Porcentajes y proporcionalidad",
        "subtitulo": "Razones, descuentos e interés",
        "descripcion": "Porcentajes, regla de tres y proporcionalidad directa e inversa.",
        "preguntas": [
            {
                "enunciado": "El 25 % de 240 es:",
                "opciones": {"A": "40", "B": "50", "C": "60", "D": "80"},
                "respuesta": "C",
                "explicacion": "25 %=1/4. 240÷4=60.",
            },
            {
                "enunciado": "En un recinto hay 120 estudiantes. El 40 % está en grado 10 y, de esos, la cuarta parte presenta Matemáticas este sábado. ¿Cuántos de grado 10 presentan Matemáticas el sábado?",
                "opciones": {"A": "12", "B": "18", "C": "24", "D": "48"},
                "respuesta": "A",
                "explicacion": "40 % de 120=48. La cuarta parte de 48 es 12.",
            },
            {
                "enunciado": "Una chaqueta cuesta $80.000. Primero le hacen 20 % de descuento y luego cobran 10 % de IVA sobre el precio ya descontado. ¿Cuál es el precio final?",
                "opciones": {"A": "$64.000", "B": "$70.400", "C": "$72.000", "D": "$88.000"},
                "respuesta": "B",
                "explicacion": "80.000×0,80=64.000. Con IVA: 64.000×1,10=70.400.",
            },
            {
                "enunciado": "6 obreros tardan 10 días en pintar un muro. ¿Cuántos días tardarían 4 obreros, al mismo ritmo, en pintar el mismo muro?",
                "opciones": {"A": "12 días", "B": "15 días", "C": "16 días", "D": "24 días"},
                "respuesta": "B",
                "explicacion": "Proporcionalidad inversa: 6×10=4×d → d=15.",
            },
            {
                "enunciado": "Un capital de $2.000.000 se coloca al 3 % mensual de interés simple durante 4 meses. Al final se retira el total y se gasta el 15 % de esa suma. ¿Cuánto queda?",
                "opciones": {"A": "$1.904.000", "B": "$2.040.000", "C": "$2.244.000", "D": "$1.870.000"},
                "respuesta": "A",
                "explicacion": "Interés: 2.000.000×0,03×4=240.000. Total 2.240.000. Queda 85 %: 1.904.000.",
            },
            {
                "enunciado": "Un artículo sube 10 % y luego baja 10 %. Si costaba $50.000, el precio final es:",
                "opciones": {"A": "$50.000", "B": "$49.500", "C": "$49.000", "D": "$45.000"},
                "respuesta": "B",
                "explicacion": "55.000 y luego 55.000×0,90=49.500.",
            },
            {
                "enunciado": "15 litros de pintura alcanzan para 45 m². ¿Cuántos litros se necesitan para 72 m², en las mismas condiciones?",
                "opciones": {"A": "22 litros", "B": "24 litros", "C": "30 litros", "D": "36 litros"},
                "respuesta": "B",
                "explicacion": "15/45=x/72 → x=24.",
            },
            {
                "enunciado": "En una receta, la razón de harina a azúcar es 5:2. Si se usan 350 g de harina, ¿cuánta azúcar se necesita?",
                "opciones": {"A": "100 g", "B": "140 g", "C": "175 g", "D": "200 g"},
                "respuesta": "B",
                "explicacion": "5 partes=350 → 1 parte=70. Azúcar: 2×70=140 g.",
            },
            {
                "enunciado": "Un descuento del 15 % sobre $40.000 equivale a ahorrar:",
                "opciones": {"A": "$4.000", "B": "$5.000", "C": "$6.000", "D": "$6.500"},
                "respuesta": "C",
                "explicacion": "0,15×40.000=6.000.",
            },
            {
                "enunciado": "Si 8 máquinas producen 400 piezas en 5 horas, ¿cuántas piezas producen 6 máquinas en 5 horas, al mismo ritmo?",
                "opciones": {"A": "250", "B": "300", "C": "320", "D": "350"},
                "respuesta": "B",
                "explicacion": "Proporcional a las máquinas: (6/8)×400=300.",
            },
            {
                "enunciado": "El 12 % de un número es 36. Ese número es:",
                "opciones": {"A": "250", "B": "280", "C": "300", "D": "432"},
                "respuesta": "C",
                "explicacion": "0,12x=36 → x=300.",
            },
            {
                "enunciado": "Un mapa usa escala 1:200.000. Una carretera de 4 cm en el mapa mide en la realidad:",
                "opciones": {"A": "2 km", "B": "4 km", "C": "8 km", "D": "80 km"},
                "respuesta": "C",
                "explicacion": "4 cm × 200.000 = 800.000 cm = 8 km.",
            },
            {
                "enunciado": "Tres números están en proporción 2:3:5 y suman 80. El mayor es:",
                "opciones": {"A": "16", "B": "24", "C": "30", "D": "40"},
                "respuesta": "D",
                "explicacion": "2k+3k+5k=80 → 10k=80 → k=8. Mayor: 40.",
            },
            {
                "enunciado": "Un salario de $1.800.000 aumenta 8 %. El nuevo salario es:",
                "opciones": {"A": "$1.944.000", "B": "$1.960.000", "C": "$2.000.000", "D": "$1.880.000"},
                "respuesta": "A",
                "explicacion": "1.800.000×1,08=1.944.000.",
            },
            {
                "enunciado": "5 obreros tardan 12 días. ¿Cuántos obreros se necesitan para terminar en 10 días, al mismo ritmo?",
                "opciones": {"A": "4", "B": "6", "C": "8", "D": "10"},
                "respuesta": "B",
                "explicacion": "5×12=60 obrero-días. 60/10=6 obreros.",
            },
            {
                "enunciado": "Un producto cuesta $25.000 más IVA del 19 %. El total a pagar es:",
                "opciones": {"A": "$27.500", "B": "$29.750", "C": "$30.000", "D": "$31.250"},
                "respuesta": "B",
                "explicacion": "25.000×1,19=29.750.",
            },
        ],
    },
    {
        "id": "Algebra",
        "titulo": "Álgebra",
        "subtitulo": "Ecuaciones, expresiones y funciones lineales",
        "descripcion": "Despejes, ecuaciones de primer grado y funciones lineales.",
        "preguntas": [
            {
                "enunciado": "Si 3x + 5 = 20, el valor de x es:",
                "opciones": {"A": "3", "B": "5", "C": "7", "D": "15"},
                "respuesta": "B",
                "explicacion": "3x=15 → x=5.",
            },
            {
                "enunciado": "Al simplificar 2(3x − 4) − (x + 6) se obtiene:",
                "opciones": {"A": "5x − 14", "B": "5x − 2", "C": "7x − 14", "D": "5x + 2"},
                "respuesta": "A",
                "explicacion": "6x−8−x−6=5x−14.",
            },
            {
                "enunciado": "La nota final es 30 % quizzes, 30 % talleres y 40 % examen. Un estudiante tiene 3,8 en quizzes y 4,2 en talleres. ¿Qué nota mínima necesita en el examen para obtener al menos 4,0?",
                "opciones": {"A": "3,9", "B": "4,0", "C": "4,1", "D": "4,2"},
                "respuesta": "B",
                "explicacion": "2,40+0,4x≥4 → x≥4,0.",
            },
            {
                "enunciado": "La edad de Ana es el doble de la de Bruno. En 6 años, la suma de sus edades será 48. ¿Cuántos años tiene Ana ahora?",
                "opciones": {"A": "18", "B": "20", "C": "24", "D": "28"},
                "respuesta": "C",
                "explicacion": "2x+x+12=48 → 3x=36 → x=12. Ana tiene 24.",
            },
            {
                "enunciado": "Un taxi cobra $4.500 de bajada más $800 por kilómetro. Si el costo total fue $12.500, ¿cuántos kilómetros se recorrieron? C(k)=4500+800k.",
                "opciones": {"A": "8 km", "B": "10 km", "C": "12 km", "D": "16 km"},
                "respuesta": "B",
                "explicacion": "12.500=4.500+800k → k=10.",
            },
            {
                "enunciado": "La solución de 2(x − 3) = 5x + 3 es:",
                "opciones": {"A": "x = −3", "B": "x = −1", "C": "x = 1", "D": "x = 3"},
                "respuesta": "A",
                "explicacion": "2x−6=5x+3 → −9=3x → x=−3.",
            },
            {
                "enunciado": "Si y = 3x − 1, cuando x = 4 el valor de y es:",
                "opciones": {"A": "7", "B": "11", "C": "12", "D": "13"},
                "respuesta": "B",
                "explicacion": "y=12−1=11.",
            },
            {
                "enunciado": "El sistema x + y = 10 y x − y = 2 tiene solución:",
                "opciones": {"A": "(4, 6)", "B": "(6, 4)", "C": "(8, 2)", "D": "(5, 5)"},
                "respuesta": "B",
                "explicacion": "Sumando: 2x=12 → x=6, y=4.",
            },
            {
                "enunciado": "Factorizar x² − 9 da:",
                "opciones": {"A": "(x−9)(x+1)", "B": "(x−3)²", "C": "(x−3)(x+3)", "D": "x(x−9)"},
                "respuesta": "C",
                "explicacion": "Diferencia de cuadrados: a²−b²=(a−b)(a+b).",
            },
            {
                "enunciado": "Si 5 − 2x > 1, entonces:",
                "opciones": {"A": "x > 2", "B": "x < 2", "C": "x > −2", "D": "x < −2"},
                "respuesta": "B",
                "explicacion": "−2x>−4 → al dividir por −2 se invierte: x<2.",
            },
            {
                "enunciado": "La pendiente de la recta que pasa por (0, 2) y (4, 10) es:",
                "opciones": {"A": "1", "B": "2", "C": "3", "D": "4"},
                "respuesta": "B",
                "explicacion": "(10−2)/(4−0)=8/4=2.",
            },
            {
                "enunciado": "Si f(x)=2x+3, entonces f(5)−f(1) es:",
                "opciones": {"A": "4", "B": "6", "C": "8", "D": "10"},
                "respuesta": "C",
                "explicacion": "f(5)=13, f(1)=5, diferencia 8.",
            },
            {
                "enunciado": "La ecuación  x/3 + 4 = 10  tiene solución:",
                "opciones": {"A": "x=2", "B": "x=6", "C": "x=18", "D": "x=42"},
                "respuesta": "C",
                "explicacion": "x/3=6 → x=18.",
            },
            {
                "enunciado": "Si (x+2)(x−5)=0, las soluciones son:",
                "opciones": {"A": "2 y −5", "B": "−2 y 5", "C": "2 y 5", "D": "−2 y −5"},
                "respuesta": "B",
                "explicacion": "x+2=0 o x−5=0 → x=−2 o x=5.",
            },
            {
                "enunciado": "Un número más su triple es 84. El número es:",
                "opciones": {"A": "21", "B": "24", "C": "28", "D": "63"},
                "respuesta": "A",
                "explicacion": "x+3x=84 → 4x=84 → x=21.",
            },
            {
                "enunciado": "La expresión (2x³)(3x²) es igual a:",
                "opciones": {"A": "5x⁵", "B": "6x⁵", "C": "6x⁶", "D": "5x⁶"},
                "respuesta": "B",
                "explicacion": "2×3=6 y 3+2=5 → 6x⁵.",
            },
        ],
    },
    {
        "id": "Geometria",
        "titulo": "Geometría",
        "subtitulo": "Áreas, perímetros, ángulos y volumen",
        "descripcion": "Figuras planas, teorema de Pitágoras y sólidos.",
        "preguntas": [
            {
                "enunciado": "Un rectángulo mide 12 cm de largo y 5 cm de ancho. ¿Cuál es su perímetro?",
                "opciones": {"A": "17 cm", "B": "34 cm", "C": "60 cm", "D": "24 cm"},
                "respuesta": "B",
                "explicacion": "2(12+5)=34 cm.",
            },
            {
                "enunciado": "Un triángulo tiene un ángulo de 50° y otro de 65°. ¿Cuánto mide el tercer ángulo?",
                "opciones": {"A": "55°", "B": "65°", "C": "75°", "D": "115°"},
                "respuesta": "B",
                "explicacion": "180−50−65=65°.",
            },
            {
                "enunciado": "Un jardín rectangular de 10 m por 6 m tiene un camino de 1 m de ancho alrededor (por fuera). ¿Cuál es el área del camino?",
                "opciones": {"A": "16 m²", "B": "32 m²", "C": "36 m²", "D": "48 m²"},
                "respuesta": "C",
                "explicacion": "Exterior 12×8=96. Interior 60. Camino 36 m².",
            },
            {
                "enunciado": "Una escalera de 13 m se apoya en un muro. La base está a 5 m de la pared. ¿A qué altura queda el extremo superior?",
                "opciones": {"A": "8 m", "B": "10 m", "C": "12 m", "D": "18 m"},
                "respuesta": "C",
                "explicacion": "h²+25=169 → h=12.",
            },
            {
                "enunciado": "Una caja de 40 cm × 25 cm × 20 cm se llena con cubos de 5 cm de arista. ¿Cuántos cubos caben sin dejar espacios?",
                "opciones": {"A": "80", "B": "120", "C": "160", "D": "200"},
                "respuesta": "C",
                "explicacion": "8×5×4=160 cubos.",
            },
            {
                "enunciado": "El área de un círculo de radio 7 cm, usando π=22/7, es:",
                "opciones": {"A": "44 cm²", "B": "88 cm²", "C": "154 cm²", "D": "308 cm²"},
                "respuesta": "C",
                "explicacion": "πr²=(22/7)×49=154.",
            },
            {
                "enunciado": "Un cuadrado y un rectángulo tienen la misma área 36 cm². El cuadrado tiene lado 6 cm. Si el rectángulo tiene base 9 cm, su altura es:",
                "opciones": {"A": "3 cm", "B": "4 cm", "C": "5 cm", "D": "6 cm"},
                "respuesta": "B",
                "explicacion": "9h=36 → h=4.",
            },
            {
                "enunciado": "En un triángulo isósceles, los ángulos de la base miden 40° cada uno. El ángulo del vértice mide:",
                "opciones": {"A": "40°", "B": "80°", "C": "100°", "D": "140°"},
                "respuesta": "C",
                "explicacion": "180−80=100°.",
            },
            {
                "enunciado": "El volumen de un cubo de arista 4 cm es:",
                "opciones": {"A": "16 cm³", "B": "48 cm³", "C": "64 cm³", "D": "96 cm³"},
                "respuesta": "C",
                "explicacion": "4³=64.",
            },
            {
                "enunciado": "Dos ángulos complementarios miden x y 2x. Entonces x es:",
                "opciones": {"A": "30°", "B": "45°", "C": "60°", "D": "90°"},
                "respuesta": "A",
                "explicacion": "x+2x=90 → x=30°.",
            },
            {
                "enunciado": "El perímetro de un triángulo equilátero de lado 9 cm es:",
                "opciones": {"A": "18 cm", "B": "27 cm", "C": "36 cm", "D": "81 cm"},
                "respuesta": "B",
                "explicacion": "3×9=27.",
            },
            {
                "enunciado": "Un trapecio tiene bases 10 cm y 6 cm, y altura 4 cm. Su área es:",
                "opciones": {"A": "24 cm²", "B": "32 cm²", "C": "40 cm²", "D": "64 cm²"},
                "respuesta": "B",
                "explicacion": "((10+6)/2)×4=32.",
            },
            {
                "enunciado": "En un rectángulo, la diagonal es 10 cm y un lado es 6 cm. El otro lado mide:",
                "opciones": {"A": "4 cm", "B": "8 cm", "C": "12 cm", "D": "16 cm"},
                "respuesta": "B",
                "explicacion": "b²+36=100 → b=8.",
            },
            {
                "enunciado": "La circunferencia de un círculo de diámetro 14 cm, con π=22/7, es:",
                "opciones": {"A": "22 cm", "B": "44 cm", "C": "88 cm", "D": "154 cm"},
                "respuesta": "B",
                "explicacion": "C=πd=(22/7)×14=44.",
            },
            {
                "enunciado": "Un prisma triangular tiene área de la base 12 cm² y altura 10 cm. Su volumen es:",
                "opciones": {"A": "60 cm³", "B": "120 cm³", "C": "144 cm³", "D": "240 cm³"},
                "respuesta": "B",
                "explicacion": "V=Ab×h=12×10=120.",
            },
            {
                "enunciado": "Ángulos opuestos por el vértice miden 3x y 75°. El valor de x es:",
                "opciones": {"A": "15", "B": "25", "C": "35", "D": "75"},
                "respuesta": "B",
                "explicacion": "Son iguales: 3x=75 → x=25.",
            },
        ],
    },
    {
        "id": "Estadistica y probabilidad",
        "titulo": "Estadística y probabilidad",
        "subtitulo": "Datos, medias y azar",
        "descripcion": "Medidas de tendencia central, lectura de datos y probabilidad.",
        "preguntas": [
            {
                "enunciado": "Las notas de un quiz fueron 2, 3, 3, 4 y 5. ¿Cuál es la moda?",
                "opciones": {"A": "2", "B": "3", "C": "4", "D": "5"},
                "respuesta": "B",
                "explicacion": "El 3 aparece dos veces.",
            },
            {
                "enunciado": "Con las notas 2, 3, 3, 4 y 5, ¿cuál es la mediana?",
                "opciones": {"A": "2", "B": "3", "C": "3,4", "D": "4"},
                "respuesta": "B",
                "explicacion": "El valor central de cinco datos ordenados es 3.",
            },
            {
                "enunciado": "2 estudiantes leyeron 1 libro, 5 leyeron 2, 8 leyeron 3 y 5 leyeron 4. ¿Cuál es la media de libros por estudiante?",
                "opciones": {"A": "2,5", "B": "2,8", "C": "3,0", "D": "3,2"},
                "respuesta": "B",
                "explicacion": "56 libros / 20 estudiantes = 2,8.",
            },
            {
                "enunciado": "En una urna hay 3 balotas rojas y 2 azules. Se extrae una al azar. ¿Cuál es la probabilidad de que no sea azul?",
                "opciones": {"A": "1/5", "B": "2/5", "C": "3/5", "D": "2/3"},
                "respuesta": "C",
                "explicacion": "3 rojas de 5: 3/5.",
            },
            {
                "enunciado": "La misma urna (3 rojas y 2 azules). Se extraen 2 balotas sin devolver. ¿Probabilidad de que ambas sean rojas?",
                "opciones": {"A": "1/5", "B": "3/10", "C": "2/5", "D": "3/5"},
                "respuesta": "B",
                "explicacion": "(3/5)×(2/4)=3/10.",
            },
            {
                "enunciado": "Los datos 4, 8, 6, 10 y 7 tienen media:",
                "opciones": {"A": "6", "B": "7", "C": "8", "D": "9"},
                "respuesta": "B",
                "explicacion": "35/5=7.",
            },
            {
                "enunciado": "En un dado justo, la probabilidad de obtener un número par es:",
                "opciones": {"A": "1/6", "B": "1/3", "C": "1/2", "D": "2/3"},
                "respuesta": "C",
                "explicacion": "2, 4 y 6: tres de seis.",
            },
            {
                "enunciado": "La mediana de 9, 2, 7, 4 y 11 es:",
                "opciones": {"A": "4", "B": "7", "C": "9", "D": "11"},
                "respuesta": "B",
                "explicacion": "Orden: 2,4,7,9,11. Centro: 7.",
            },
            {
                "enunciado": "Se lanza una moneda dos veces. La probabilidad de dos caras es:",
                "opciones": {"A": "1/4", "B": "1/3", "C": "1/2", "D": "3/4"},
                "respuesta": "A",
                "explicacion": "(1/2)×(1/2)=1/4.",
            },
            {
                "enunciado": "En una encuesta, 18 de 60 estudiantes prefieren fútbol. ¿Qué porcentaje es?",
                "opciones": {"A": "18 %", "B": "25 %", "C": "30 %", "D": "40 %"},
                "respuesta": "C",
                "explicacion": "18/60=0,30=30 %.",
            },
            {
                "enunciado": "Un conjunto tiene moda 5 y todos los datos son distintos excepto dos que valen 5. Si hay 6 datos, ¿cuántas veces aparece el 5?",
                "opciones": {"A": "1", "B": "2", "C": "3", "D": "6"},
                "respuesta": "B",
                "explicacion": "La moda es el valor que más se repite; aquí el 5 aparece dos veces.",
            },
            {
                "enunciado": "De 10 canicas, 4 son verdes. Se saca una. P(verde) es:",
                "opciones": {"A": "1/10", "B": "2/5", "C": "3/5", "D": "4/6"},
                "respuesta": "B",
                "explicacion": "4/10=2/5.",
            },
            {
                "enunciado": "El rango de 3, 9, 4, 12 y 6 es:",
                "opciones": {"A": "6", "B": "9", "C": "12", "D": "15"},
                "respuesta": "B",
                "explicacion": "Máximo 12 menos mínimo 3 = 9.",
            },
            {
                "enunciado": "Si P(A)=0,3 y A y B son mutuamente excluyentes con P(B)=0,5, entonces P(A o B) es:",
                "opciones": {"A": "0,15", "B": "0,2", "C": "0,8", "D": "1,0"},
                "respuesta": "C",
                "explicacion": "P(A∪B)=P(A)+P(B)=0,8.",
            },
            {
                "enunciado": "Una urna tiene 2 blancas y 3 negras. Se saca una, se mira y se devuelve, y se saca otra. P(ambas blancas) es:",
                "opciones": {"A": "4/25", "B": "1/10", "C": "2/5", "D": "4/20"},
                "respuesta": "A",
                "explicacion": "Con reemplazo: (2/5)×(2/5)=4/25.",
            },
            {
                "enunciado": "Cinco puntajes: 10, 20, 30, 40 y 50. Si se agrega 30, la media:",
                "opciones": {"A": "baja", "B": "sube", "C": "no cambia", "D": "se vuelve 25"},
                "respuesta": "C",
                "explicacion": "La media original ya es 30; agregar 30 no la altera.",
            },
        ],
    },
]


def corregir_aritmetica():
    for tema in TEMAS:
        if tema["id"] != "Aritmetica":
            continue
        for p in tema["preguntas"]:
            if "1.000 entre 7" in p["enunciado"]:
                p["respuesta"] = "D"
                p["explicacion"] = "7×142=994 y 1.000−994=6."
